server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootBlogHikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml